[
  {'check_plugin_name': 'cmk_site_statistics', 'item': 'cmk', 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'cpu_utilization_os', 'item': None, 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'livestatus_status', 'item': 'cmk', 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'lnx_if', 'item': '2', 'parameters': {'discovered_oper_status': ['1'], 'discovered_speed': 10000000000}, 'service_labels': {}},
  {'check_plugin_name': 'mem_used', 'item': None, 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'mkeventd_status', 'item': 'cmk', 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'mounts', 'item': '/usr/share/zoneinfo/UCT', 'parameters': ['data=ordered', 'discard', 'errors=remount-ro', 'relatime', 'ro'], 'service_labels': {}},
  {'check_plugin_name': 'omd_apache', 'item': 'cmk', 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'omd_status', 'item': 'cmk', 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'postfix_mailq', 'item': '', 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'postfix_mailq_status', 'item': '', 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'tcp_conn_stats', 'item': None, 'parameters': {}, 'service_labels': {}},
  {'check_plugin_name': 'uptime', 'item': None, 'parameters': {}, 'service_labels': {}},
]
